name: covid19-pets
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - jupyterlab
  - matplotlib=3.2.2
  - numpy=1.18.3
  - pandas=1.0.5
  - python=3.7.6
  - seaborn=0.10.1
  - pip:
    - biopython
